name: Main Build Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Project One
        uses: ./.github/workflows/projectOne-build.yml

      - name: Build Project Two
        uses: ./.github/workflows/projectTwo-build.yml
