name: Build and Upload Projects to JFrog

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Set Timestamp
      id: build
      run: echo "timestamp=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    # ProjectOne build
    - name: Build ProjectOne
      run: dotnet build src/ProjectOne/ProjectOne.csproj --configuration Release
      id: build-one

    # ProjectTwo build
    - name: Build ProjectTwo
      run: dotnet build src/ProjectTwo/ProjectTwo.csproj --configuration Release
      id: build-two

    # Upload ProjectOne Artifacts to JFrog
    - name: Upload ProjectOne Artifacts to JFrog
      run: |
        curl -u "${{ secrets.JFROG_USERNAME }}:${{ secrets.JFROG_API_KEY }}" \
        -T src/ProjectOne/bin/Release/net6.0/ProjectOne.dll \
        "https://rohini4258.jfrog.io/artifactory/api/generic/projectone-artifacts-generic-local/ProjectOne-${{ env.timestamp }}.dll"
      shell: /usr/bin/bash -e {0}

    # Upload ProjectTwo Artifacts to JFrog
    - name: Upload ProjectTwo Artifacts to JFrog
      run: |
        curl -u "${{ secrets.JFROG_USERNAME }}:${{ secrets.JFROG_API_KEY }}" \
        -T src/ProjectTwo/bin/Release/net6.0/ProjectTwo.dll \
        "https://rohini4258.jfrog.io/artifactory/api/generic/projecttwo-artifacts-generic-local/ProjectTwo-${{ env.timestamp }}.dll"
      shell: /usr/bin/bash -e {0}
