name: Build and Deploy Projects to JFrog

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Build Project
        run: |
          cd src/${{ inputs.project }}
          dotnet build --configuration Release

      - name: Version Artifacts
        id: versioning
        run: |
          timestamp=$(date +'%Y%m%d%H%M%S')
          echo "timestamp=$timestamp" >> $GITHUB_ENV

      - name: Publish Artifacts Locally
        run: |
          mkdir -p ../../artifacts/${{ inputs.project }}
          cp src/${{ inputs.project }}/bin/Release/net8.0/*.dll ../../artifacts/${{ inputs.project }}/${{ inputs.project }}-${{ env.timestamp }}.dll

      - name: List Artifacts
        run: |
          echo "Listing Artifacts for ${{ inputs.project }}:"
          ls -la ../../artifacts/${{ inputs.project }}

      # Upload to JFrog Repository
      - name: Upload Artifacts to JFrog
        run: |
          curl -u "${{ secrets.JFROG_USERNAME }}:${{ secrets.JFROG_API_KEY }}" \
          -T ../../artifacts/${{ inputs.project }}/${{ inputs.project }}-${{ env.timestamp }}.dll \
          "https://rohini4258.jfrog.io/artifactory/api/generic/${{ inputs.project }}-artifacts-generic-local/${{ inputs.project }}-${{ env.timestamp }}.dll"
        shell: /usr/bin/bash -e {0}
