name: Build Projects

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Build Project
        run: |
          cd src/${{ inputs.project }}
          dotnet build --configuration Release

      - name: Publish Artifacts
        run: |
          mkdir -p ../../artifacts/${{ inputs.project }}
          cp src/${{ inputs.project }}/bin/Release/net8.0/*.dll ../../artifacts/${{ inputs.project }}/

      - name: List Artifacts
        run: |
          echo "Listing Artifacts for ${{ inputs.project }}:"
          ls -la ../../artifacts/${{ inputs.project }}/
