name: Deploy All Projects

on:
  workflow_run:
    workflows: ["Build All Projects"]
    types:
      - completed

jobs:
  deploy-project-one:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Project One to AKS
        run: |
          echo "Deploying Project One..."
          # Add Azure CLI commands here to deploy to AKS
          # For example:
          # az aks get-credentials --resource-group <resource-group> --name <aks-cluster-name>
          # kubectl apply -f path/to/ProjectOne/deployment.yaml

  deploy-project-two:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Project Two to AKS
        run: |
          echo "Deploying Project Two..."
          # Add Azure CLI commands here to deploy to AKS
          # For example:
          # az aks get-credentials --resource-group <resource-group> --name <aks-cluster-name>
          # kubectl apply -f path/to/ProjectTwo/deployment.yaml
