# .github/workflows/projectOne-build.yml
name: Project One Build

on:
  push:
    branches:
      - master  # Change as needed

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      project: 'ProjectOne'
