name: Build Project Two

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Build and Publish Project Two
        run: |
          cd src/ProjectTwo
          dotnet build --configuration Release
          dotnet publish --configuration Release --output ../../artifacts/ProjectTwo

      - name: Generate Timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Versioned Build Artifacts
        run: |
          mv ../../artifacts/ProjectTwo ../../artifacts/ProjectTwo-${{ env.TIMESTAMP }}

      # - name: Install JFrog CLI
      #   run: curl -fL https://getcli.jfrog.io | sh

      # - name: Upload to JFrog
      #   run: |
      #     ./jfrog rt upload "artifacts/ProjectTwo-${{ env.TIMESTAMP }}/*" "my-repo/path/to/store/artifacts/"
