# .github/workflows/projectTwo-build.yml
name: Project Two Build

on:
  push:
    branches:
      - master  # Change as needed

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      project: 'ProjectTwo'
